name: spring-petclinic-ci

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install JFrog CLI (full version)
        run: |
          curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/latest/jf-linux-amd64/jf -o jf
          chmod +x jf
          sudo mv jf /usr/local/bin/

      - name: Configure JFrog CLI
        run: |
          jf c add jfrog-server \
            --url="${{ secrets.JF_URL }}" \
            --user="${{ secrets.JF_USER }}" \
            --password="${{ secrets.JF_PASSWORD }}" \
            --interactive=false

      - name: Build with Maven (using JFrog virtual repo)
        run: mvn clean package -s settings.xml

      - name: Upload JAR to Artifactory
        run: |
          jf rt upload "target/*.jar" \
            "libs-release-local/spring-petclinic/${{ github.run_number }}/" \
            --flat=true

      - name: Xray Scan the Artifact
        run: |
          jf xr scan \
            "libs-release-local/spring-petclinic/${{ github.run_number }}/" \
            --fail=false
