name: spring-petclinic-ci

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install JFrog CLI (thin version)
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/jf

      - name: Configure JFrog CLI
        run: |
          jf c add jfrog-server \
            --url="${{ secrets.JF_URL }}" \
            --user="${{ secrets.JF_USER }}" \
            --password="${{ secrets.JF_PASSWORD }}" \
            --interactive=false

      - name: Build with Maven (using JFrog virtual repo)
        run: mvn clean package -s settings.xml

      - name: Upload JAR to Artifactory
        run: |
          jf rt upload "target/*.jar" \
            "libs-release-local/spring-petclinic/${{ github.run_number }}/" \
            --flat=true
